name = "dreamtales"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "dreamtales-worker"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "3b9edcfd503a4f8daf8940f2c1a87648"
preview_id = "3b9edcfd503a4f8daf8940f2c1a87648"

[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = ""

# Repository information
[triggers]
crons = [] 