name = "dreamtales"
main = "worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enable preview URLs for testing
preview_urls = true

# Static assets configuration (for Cloudflare Git deployment)
[assets]
directory = "client/build"
not_found_handling = "single-page-application"
binding = "ASSETS"

# KV namespace for chat history (managed via Cloudflare dashboard)
[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "3b9edcfd503a4f8daf8940f2c1a87648"
preview_id = "3b9edcfd503a4f8daf8940f2c1a87648"

# KV namespace for configuration data (managed via Cloudflare dashboard)
[[kv_namespaces]]
binding = "CONFIG"
id = "99c6af77c41041c8b7fcc8ed7e59685f"
preview_id = "99c6af77c41041c8b7fcc8ed7e59685f"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Build handled by Cloudflare's Git integration via package.json build script
# No custom build command needed 